sonar.projectKey=naveen-raj_multi-tenant-e-commerce-platform
sonar.organization=naveen-raj
sonar.projectName=Multi-Tenant E-Commerce Platform

sonar.sources=app

sonar.exclusions=client/**,**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8

sonar.python.version=3.14