sonar.projectKey=multi-tenant-ecommerce
sonar.projectName=Multi-Tenant E-Commerce Platform
sonar.organization=naveenraj19353-prog

sonar.sources=app
sonar.exclusions=client/**

sonar.sourceEncoding=UTF-8