import type { ThemeColors } from "./types";
import { DEFAULT_THEME_COLORS } from "./types";

/** Quick single-colour presets shown as chips in the Colors tab. */
export const COLOR_PRESET_NAMES = ["green", "blue", "purple", "orange", "dark"] as const;

/** Full store templates shipped in the Themes library (colours + layout + font). */
export const THEME_TEMPLATE_NAMES = [
    "editorial-noir",
    "rosewood-boutique",
    "nordic-slate",
    "midnight-gold",
    "electric-pop",
    "aurelia",
    "urbanly",
    "blossom",
    "techhub",
    "shopcart",
    "elanza",
    "sportx",
    "freshmart",
    "homesia",
    "ratnaa",
    "gadgetx",
    "kiddo",
    "glowra",
    "vertex",
    "artisan",
] as const;

/**
 * Every named theme. A store's saved `theme` is resolved against this list, so
 * library templates must stay registered here even though they are applied
 * through themeLibrary.ts.
 */
export const THEME_PRESET_NAMES = [
    ...COLOR_PRESET_NAMES,
    ...THEME_TEMPLATE_NAMES,
] as const;

export type ColorPresetName = (typeof COLOR_PRESET_NAMES)[number];
export type ThemeTemplateName = (typeof THEME_TEMPLATE_NAMES)[number];
export type ThemePresetName = (typeof THEME_PRESET_NAMES)[number];

export const themePresets: Record<ThemePresetName, ThemeColors> = {
    green: {
        ...DEFAULT_THEME_COLORS,
        primary: "#EA580C",
        secondary: "#F97316",
    },
    blue: {
        ...DEFAULT_THEME_COLORS,
        primary: "#2563EB",
        secondary: "#3B82F6",
        headerBackground: "#EFF6FF",
    },
    purple: {
        ...DEFAULT_THEME_COLORS,
        primary: "#7C3AED",
        secondary: "#8B5CF6",
        headerBackground: "#F5F3FF",
    },
    orange: {
        ...DEFAULT_THEME_COLORS,
        primary: "#EA580C",
        secondary: "#F97316",
        headerBackground: "#FFF7ED",
        background: "#FFFBEB",
        border: "#FDE68A",
    },
    dark: {
        ...DEFAULT_THEME_COLORS,
        primary: "#22C55E",
        secondary: "#16A34A",
        headerBackground: "#172033",
        background: "#0F172A",
        surface: "#1E293B",
        border: "#334155",
        textBlack: "#F8FAFC",
        textWhite: "#0F172A",
    },
    /* --- Themes library: the first five -------------------------------- */
    "editorial-noir": {
        primary: "#1C1917",
        secondary: "#57534E",
        headerBackground: "#FFFFFF",
        background: "#FAFAF9",
        surface: "#FFFFFF",
        border: "#E7E5E4",
        textBlack: "#1C1917",
        textWhite: "#FFFFFF",
        success: "#047857",
        warning: "#B45309",
        danger: "#B91C1C",
    },
    "rosewood-boutique": {
        primary: "#9F1239",
        secondary: "#BE123C",
        headerBackground: "#FFF1F2",
        background: "#FFFBF7",
        surface: "#FFFFFF",
        border: "#F3D6DC",
        textBlack: "#2A1519",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#BE123C",
    },
    "nordic-slate": {
        primary: "#334155",
        secondary: "#475569",
        headerBackground: "#F1F5F9",
        background: "#F8FAFC",
        surface: "#FFFFFF",
        border: "#CBD5E1",
        textBlack: "#0F172A",
        textWhite: "#FFFFFF",
        success: "#047857",
        warning: "#B45309",
        danger: "#DC2626",
    },
    "midnight-gold": {
        primary: "#C8A96A",
        secondary: "#E0C48A",
        headerBackground: "#111827",
        background: "#0B1120",
        surface: "#151E31",
        border: "#2A3550",
        textBlack: "#F5F3EE",
        /* Inverted: button labels sit on the gold plate. */
        textWhite: "#0B1120",
        success: "#34D399",
        warning: "#FBBF24",
        danger: "#F87171",
    },
    "electric-pop": {
        primary: "#4F46E5",
        secondary: "#7C3AED",
        headerBackground: "#EEF2FF",
        background: "#FAFAFF",
        surface: "#FFFFFF",
        border: "#E0E7FF",
        textBlack: "#111827",
        textWhite: "#FFFFFF",
        success: "#16A34A",
        warning: "#F59E0B",
        danger: "#EF4444",
    },
    /* --- Themes library: reference sheet 1 ----------------------------- */
    aurelia: {
        primary: "#2E2A26",
        secondary: "#6B5B4A",
        headerBackground: "#F7F1E8",
        background: "#FAF5EE",
        surface: "#FFFFFF",
        border: "#E7DCCC",
        textBlack: "#2B2620",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#B91C1C",
    },
    urbanly: {
        primary: "#D9F24A",
        secondary: "#EAFA7E",
        headerBackground: "#0D0D0D",
        background: "#0D0D0D",
        surface: "#1A1A1A",
        border: "#2A2A2A",
        textBlack: "#F5F5F5",
        /* Ink label on the lime plate. */
        textWhite: "#0D0D0D",
        success: "#4ADE80",
        warning: "#FBBF24",
        danger: "#F87171",
    },
    blossom: {
        primary: "#4A5D3F",
        secondary: "#6B7F5E",
        headerBackground: "#F2EFE6",
        background: "#FBF6EF",
        surface: "#FFFFFF",
        border: "#E6E0D3",
        textBlack: "#22301F",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#B91C1C",
    },
    techhub: {
        primary: "#2563EB",
        secondary: "#3B82F6",
        headerBackground: "#F5F8FC",
        background: "#F8FAFC",
        surface: "#FFFFFF",
        border: "#DBEAFE",
        textBlack: "#0F172A",
        textWhite: "#FFFFFF",
        success: "#059669",
        warning: "#B45309",
        danger: "#DC2626",
    },
    shopcart: {
        primary: "#DC2626",
        secondary: "#F97316",
        headerBackground: "#FEF2F2",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        border: "#FECACA",
        textBlack: "#111827",
        textWhite: "#FFFFFF",
        success: "#16A34A",
        warning: "#D97706",
        danger: "#DC2626",
    },
    /* --- Themes library: reference sheet 2 ----------------------------- */
    elanza: {
        primary: "#4B3F35",
        secondary: "#7A6A5C",
        headerBackground: "#F6F1EA",
        background: "#FAF7F3",
        surface: "#FFFFFF",
        border: "#E8DFD3",
        textBlack: "#2E2620",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#B91C1C",
    },
    sportx: {
        primary: "#BE123C",
        secondary: "#E11D48",
        headerBackground: "#0B0B0B",
        background: "#0B0B0B",
        surface: "#1C1C1C",
        border: "#2E2E2E",
        textBlack: "#FAFAFA",
        textWhite: "#FFFFFF",
        success: "#4ADE80",
        warning: "#FBBF24",
        danger: "#FB7185",
    },
    freshmart: {
        primary: "#15803D",
        secondary: "#22C55E",
        headerBackground: "#ECFDF5",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        border: "#BBF7D0",
        textBlack: "#14532D",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#DC2626",
    },
    homesia: {
        primary: "#3F6B5A",
        secondary: "#5E8A76",
        headerBackground: "#EFF4F0",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        border: "#D6E2DA",
        textBlack: "#1F2A24",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#B91C1C",
    },
    ratnaa: {
        primary: "#8B1D2C",
        secondary: "#A9873A",
        headerBackground: "#FBF3E6",
        background: "#FBF6EE",
        surface: "#FFFFFF",
        border: "#EADBC4",
        textBlack: "#3A1F22",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#8B1D2C",
    },
    gadgetx: {
        primary: "#1D4ED8",
        secondary: "#3B82F6",
        headerBackground: "#EFF4FF",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        border: "#DBEAFE",
        textBlack: "#0B1220",
        textWhite: "#FFFFFF",
        success: "#059669",
        warning: "#B45309",
        danger: "#DC2626",
    },
    kiddo: {
        primary: "#6D28D9",
        secondary: "#8B5CF6",
        headerBackground: "#F5F3FF",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        border: "#E9D5FF",
        textBlack: "#1F1235",
        textWhite: "#FFFFFF",
        success: "#16A34A",
        warning: "#D97706",
        danger: "#DC2626",
    },
    glowra: {
        primary: "#DB2777",
        secondary: "#F472B6",
        headerBackground: "#FDF2F8",
        background: "#FFFBFD",
        surface: "#FFFFFF",
        border: "#FBCFE8",
        textBlack: "#3B1B24",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#BE123C",
    },
    vertex: {
        primary: "#2F3E33",
        secondary: "#4A5D4E",
        headerBackground: "#F4F6F4",
        background: "#FFFFFF",
        surface: "#FFFFFF",
        border: "#DCE3DD",
        textBlack: "#111827",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#B91C1C",
    },
    artisan: {
        primary: "#B45309",
        secondary: "#C08A3E",
        headerBackground: "#FBF4E9",
        background: "#FBF7F0",
        surface: "#FFFFFF",
        border: "#E8DCC6",
        textBlack: "#3B2A1E",
        textWhite: "#FFFFFF",
        success: "#15803D",
        warning: "#B45309",
        danger: "#B91C1C",
    },
};

export const presetLabels: Record<ThemePresetName, string> = {
    green: "Forest Green",
    blue: "Ocean Blue",
    purple: "Royal Purple",
    orange: "Sunset Orange",
    dark: "Midnight Dark",
    "editorial-noir": "Editorial Noir",
    "rosewood-boutique": "Rosewood Boutique",
    "nordic-slate": "Nordic Slate",
    "midnight-gold": "Midnight Gold",
    "electric-pop": "Electric Pop",
    aurelia: "Aurelia",
    urbanly: "Urbanly",
    blossom: "Blossom",
    techhub: "TechHub",
    shopcart: "ShopCart",
    elanza: "Elanza",
    sportx: "SportX",
    freshmart: "FreshMart",
    homesia: "Homesia",
    ratnaa: "Ratnaa",
    gadgetx: "GadgetX",
    kiddo: "Kiddo",
    glowra: "Glowra",
    vertex: "Vertex",
    artisan: "Artisan",
};
