import { themePresets, type ThemeTemplateName } from "./themePresets";
import type { LayoutSettings, ThemeColors } from "./types";

/**
 * A ready-made store look. Unlike a colour preset (which only swaps colours),
 * a library template moves palette, layout and font together, so applying one
 * produces a complete direction rather than a recolour.
 *
 * `layout` holds only the deltas; anything omitted keeps the store's current
 * setting, which is what makes a template safe to apply on a configured store.
 */
export interface ThemeTemplate {
    id: ThemeTemplateName;
    label: string;
    /** The kinds of catalogue this direction suits. */
    bestFor: string;
    /** One line on what makes the direction distinct. */
    description: string;
    /** Short chips shown on the card. */
    tags: string[];
    colors: ThemeColors;
    layout: Partial<LayoutSettings>;
}

export const THEME_LIBRARY: ThemeTemplate[] = [
    {
        id: "editorial-noir",
        label: "Editorial Noir",
        bestFor: "Luxury eyewear, jewellery, couture",
        description:
            "Gallery-like and near-monochrome. Photography leads, type is serif, and nothing shouts a discount.",
        tags: ["Sharp corners", "Minimal cards", "Portrait images", "Serif type"],
        colors: themePresets["editorial-noir"],
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "minimal",
            productListingLayout: "filters-top",
            productGridColumns: 3,
            showDiscountBadge: false,
            showProductRating: false,
            productCardImageRatio: "portrait",
            pageWidth: "narrow",
            homeBannerStyle: "contained",
            productDetailLayout: "gallery-right",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "rosewood-boutique",
        label: "Rosewood Boutique",
        bestFor: "Beauty, artisan goods, gifting, kids",
        description:
            "Soft and tactile. Rosewood accents, warm off-white paper, centred card copy and generous rounding.",
        tags: ["Soft corners", "Studio cards", "Centred copy", "Sidebar filters"],
        colors: themePresets["rosewood-boutique"],
        layout: {
            cardStyle: "soft",
            sectionSpacing: "comfortable",
            productCardDesign: "studio",
            productListingLayout: "sidebar-left",
            productGridColumns: 3,
            showDiscountBadge: true,
            showProductRating: true,
            productCardImageRatio: "portrait",
            pageWidth: "standard",
            homeBannerStyle: "contained",
            cartLayout: "split",
            fontFamily: "dm-sans",
        },
    },
    {
        id: "nordic-slate",
        label: "Nordic Slate",
        bestFor: "Electronics, tools, hardware, wholesale",
        description:
            "Functional and scannable. One neutral hue, square images, top filter bar and a denser grid.",
        tags: ["Rounded corners", "Classic cards", "Square images", "Dense 4-up"],
        colors: themePresets["nordic-slate"],
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "classic",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "wide",
            stickyHeader: true,
            fontFamily: "inter",
        },
    },
    {
        id: "midnight-gold",
        label: "Midnight Gold",
        bestFor: "Watches, spirits, premium gifting",
        description:
            "Ink canvas with a champagne-gold call to action. Button text is inverted so the gold reads as a plate.",
        tags: ["Dark canvas", "Sharp corners", "Studio cards", "Gold CTA"],
        colors: themePresets["midnight-gold"],
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "studio",
            productGridColumns: 3,
            showDiscountBadge: false,
            showProductRating: false,
            productCardImageRatio: "portrait",
            productDetailLayout: "gallery-left",
            pageWidth: "standard",
            homeBannerStyle: "full",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "electric-pop",
        label: "Electric Pop",
        bestFor: "Fast fashion, gadgets, D2C",
        description:
            "Loud and conversion-led. Saturated indigo, discount badges, wishlist moved left, dense grid.",
        tags: ["Soft corners", "Classic cards", "Badges on", "Sticky header"],
        colors: themePresets["electric-pop"],
        layout: {
            cardStyle: "soft",
            sectionSpacing: "comfortable",
            productCardDesign: "classic",
            productListingLayout: "sidebar-left",
            productGridColumns: 4,
            showDiscountBadge: true,
            showQuickAddOnCard: true,
            showProductRating: true,
            productCardImageRatio: "square",
            wishlistIconPosition: "left",
            headerSearchPosition: "center",
            stickyHeader: true,
            pageWidth: "wide",
            fontFamily: "poppins",
        },
    },
    /* --- Reference sheet 1 --------------------------------------------- */
    {
        id: "aurelia",
        label: "Aurelia",
        bestFor: "Luxury eyewear, jewellery, couture",
        description:
            "Editorial ivory and espresso. Photography and serif type carry the page; no discount language anywhere.",
        tags: ["Sharp corners", "Classic cards", "Portrait images", "Serif type"],
        colors: themePresets.aurelia,
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "classic",
            productListingLayout: "sidebar-left",
            productGridColumns: 4,
            showDiscountBadge: false,
            showProductRating: false,
            productCardImageRatio: "portrait",
            pageWidth: "standard",
            homeBannerStyle: "full",
            productDetailLayout: "gallery-right",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "urbanly",
        label: "Urbanly",
        bestFor: "Streetwear, sneakers, youth D2C",
        description:
            "Ink canvas with a lime highlight block. Heavy uppercase type, dark cards with light text, dense grid.",
        tags: ["Dark canvas", "Light-on-dark cards", "Lime accent", "Sticky header"],
        colors: themePresets.urbanly,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "studio",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showQuickAddOnCard: true,
            wishlistIconPosition: "left",
            productCardImageRatio: "square",
            headerSearchPosition: "center",
            stickyHeader: true,
            pageWidth: "wide",
            fontFamily: "inter",
        },
    },
    {
        id: "blossom",
        label: "Blossom",
        bestFor: "Organic beauty, skincare, wellness",
        description:
            "Cream paper with a deep olive call to action. Airy cards, green prices, restrained borders.",
        tags: ["Soft corners", "Studio cards", "Airy spacing", "Serif type"],
        colors: themePresets.blossom,
        layout: {
            cardStyle: "soft",
            sectionSpacing: "comfortable",
            productCardDesign: "studio",
            productListingLayout: "sidebar-left",
            productGridColumns: 3,
            showDiscountBadge: false,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "standard",
            homeBannerStyle: "contained",
            fontFamily: "dm-sans",
        },
    },
    {
        id: "techhub",
        label: "TechHub",
        bestFor: "Electronics, laptops, audio, smart home",
        description:
            "Cool off-white with a confident blue. Square images, top filter bar, four-up rows for a wide catalogue.",
        tags: ["Rounded corners", "Classic cards", "Square images", "Dense 4-up"],
        colors: themePresets.techhub,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "classic",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "wide",
            stickyHeader: true,
            fontFamily: "inter",
        },
    },
    {
        id: "shopcart",
        label: "ShopCart",
        bestFor: "Multi-category marketplace, flash deals",
        description:
            "Red and orange on white with the densest grid of the set. Badges, ratings and quick add all on.",
        tags: ["Rounded corners", "Classic cards", "Badges on", "Search centred"],
        colors: themePresets.shopcart,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "classic",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showQuickAddOnCard: true,
            showProductRating: true,
            productCardImageRatio: "square",
            stickyHeader: true,
            pageWidth: "wide",
            fontFamily: "inter",
        },
    },
    /* --- Reference sheet 2 --------------------------------------------- */
    {
        id: "elanza",
        label: "Elanza",
        bestFor: "Ethnic wear, sarees, kurtas, lehengas",
        description:
            "Warm neutral and dark brown, quietly luxurious. Minimal cards with barely-there borders.",
        tags: ["Sharp corners", "Minimal cards", "Portrait images", "Serif type"],
        colors: themePresets.elanza,
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "minimal",
            productListingLayout: "sidebar-left",
            productGridColumns: 4,
            showDiscountBadge: false,
            productCardImageRatio: "portrait",
            pageWidth: "narrow",
            homeBannerStyle: "contained",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "sportx",
        label: "SportX",
        bestFor: "Sportswear, footwear, outdoor gear",
        description:
            "Carbon black with a crimson call to action. Energetic, wide, built for four-up browsing.",
        tags: ["Dark canvas", "Light-on-dark cards", "Crimson accent", "Dense 4-up"],
        colors: themePresets.sportx,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "studio",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showQuickAddOnCard: true,
            wishlistIconPosition: "left",
            productCardImageRatio: "square",
            stickyHeader: true,
            pageWidth: "wide",
            fontFamily: "inter",
        },
    },
    {
        id: "freshmart",
        label: "FreshMart",
        bestFor: "Grocery, staples, daily essentials",
        description:
            "White and green, scannable and trustworthy. Built for large catalogues with unit-based pricing.",
        tags: ["Rounded corners", "Classic cards", "Sidebar filters", "Dense 4-up"],
        colors: themePresets.freshmart,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "classic",
            productListingLayout: "sidebar-left",
            productGridColumns: 4,
            showDiscountBadge: true,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "wide",
            fontFamily: "inter",
        },
    },
    {
        id: "homesia",
        label: "Homesia",
        bestFor: "Furniture, decor, home & living",
        description:
            "White with a muted sage green. Room to breathe: three-up grid, landscape imagery, softer corners.",
        tags: ["Soft corners", "Classic cards", "Landscape images", "Three-up"],
        colors: themePresets.homesia,
        layout: {
            cardStyle: "soft",
            sectionSpacing: "comfortable",
            productCardDesign: "classic",
            productListingLayout: "sidebar-left",
            productGridColumns: 3,
            showDiscountBadge: false,
            showProductRating: true,
            productCardImageRatio: "landscape",
            pageWidth: "standard",
            fontFamily: "dm-sans",
        },
    },
    {
        id: "ratnaa",
        label: "Ratnaa",
        bestFor: "Gold, diamond and silver jewellery",
        description:
            "Cream and maroon with gold accents. Hallmark-first trust strip, square tiles, serif headings.",
        tags: ["Sharp corners", "Studio cards", "Square images", "Serif type"],
        colors: themePresets.ratnaa,
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "studio",
            productListingLayout: "sidebar-left",
            productGridColumns: 4,
            showDiscountBadge: false,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "standard",
            homeBannerStyle: "contained",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "gadgetx",
        label: "GadgetX",
        bestFor: "Mobiles, laptops, wearables, appliances",
        description:
            "Deep blue on white with navy deal panels. Studio cards so the tile does the selling.",
        tags: ["Rounded corners", "Studio cards", "Square images", "Dense 4-up"],
        colors: themePresets.gadgetx,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "compact",
            productCardDesign: "studio",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "wide",
            fontFamily: "inter",
        },
    },
    {
        id: "kiddo",
        label: "Kiddo",
        bestFor: "Toys, kids fashion, baby care, books",
        description:
            "Playful violet with pastel tints. Soft corners and rounded type keep it friendly rather than cheap.",
        tags: ["Soft corners", "Studio cards", "Playful accent", "Rounded type"],
        colors: themePresets.kiddo,
        layout: {
            cardStyle: "soft",
            sectionSpacing: "comfortable",
            productCardDesign: "studio",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: true,
            showQuickAddOnCard: true,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "standard",
            fontFamily: "poppins",
        },
    },
    {
        id: "glowra",
        label: "Glowra",
        bestFor: "Skincare, haircare, makeup, fragrance",
        description:
            "Blush pink and rose. Soft tiles, serif display type, three-up so each product gets room.",
        tags: ["Soft corners", "Studio cards", "Blush palette", "Serif type"],
        colors: themePresets.glowra,
        layout: {
            cardStyle: "soft",
            sectionSpacing: "comfortable",
            productCardDesign: "studio",
            productListingLayout: "sidebar-left",
            productGridColumns: 3,
            showDiscountBadge: true,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "standard",
            homeBannerStyle: "contained",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "vertex",
        label: "Vertex",
        bestFor: "Men's fashion, shirts, jeans, footwear",
        description:
            "White with a deep sage accent. The most stripped-back of the set: minimal cards, no badges.",
        tags: ["Sharp corners", "Minimal cards", "Portrait images", "Uppercase labels"],
        colors: themePresets.vertex,
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "minimal",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showDiscountBadge: false,
            showProductRating: false,
            productCardImageRatio: "portrait",
            pageWidth: "standard",
            fontFamily: "inter",
        },
    },
    {
        id: "artisan",
        label: "Artisan",
        bestFor: "Handmade, crafts, festive gifts, decor",
        description:
            "Cream and terracotta with gold. Warm and crafted: three-up grid, artisan trust strip, serif type.",
        tags: ["Rounded corners", "Classic cards", "Warm palette", "Serif type"],
        colors: themePresets.artisan,
        layout: {
            cardStyle: "rounded",
            sectionSpacing: "comfortable",
            productCardDesign: "classic",
            productListingLayout: "sidebar-left",
            productGridColumns: 3,
            showDiscountBadge: false,
            showProductRating: true,
            productCardImageRatio: "square",
            pageWidth: "standard",
            homeBannerStyle: "contained",
            fontFamily: "playfair-display",
        },
    },
    {
        id: "anaya",
        label: "Anaya",
        bestFor: "Bridal, festive and handwoven fashion",
        description:
            "Warm ivory paper with deep plum ink and a serif display. Products come before any promo band.",
        tags: ["Sharp corners", "Minimal cards", "No badges", "Category circles"],
        colors: themePresets.anaya,
        layout: {
            cardStyle: "sharp",
            sectionSpacing: "spacious",
            productCardDesign: "minimal",
            productListingLayout: "filters-top",
            productGridColumns: 4,
            showHomeBanner: true,
            showCategorySlider: true,
            showTestimonials: true,
            showDealOfTheDay: false,
            showDiscountBadge: false,
            showProductRating: false,
            showQuickAddOnCard: false,
            productCardImageRatio: "portrait",
            pageWidth: "standard",
            homeBannerStyle: "full",
            wishlistIconPosition: "right",
            headerSearchPosition: "right",
            stickyHeader: true,
            // The reference flow: hero, then category circles, then products,
            // with social proof after the grid and promos pushed to the end.
            homeSectionOrder: [
                "banner",
                "categories",
                "trending",
                "newArrivals",
                "mostSelling",
                "topRated",
                "testimonials",
                "festival",
                "discounts",
                "dealOfTheDay",
            ],
            fontFamily: "playfair-display",
        },
    },
];

export const findThemeTemplate = (id: string): ThemeTemplate | undefined =>
    THEME_LIBRARY.find((template) => template.id === id);
